
build:
	@spm build
	@echo "spm build ok"
	
deploy:
	@rm -rf ..\..\sea-modules\test\test1\0.0.1
	@mkdir  ..\..\sea-modules\test\test1\0.0.1

	@cp     dist/*.* ..\..\sea-modules\test\test1\0.0.1

	@echo   " deploy to sea-modules\test\test1\0.0.1"
